### PR TITLE
build-sync: Add support for re-triggering aarch64 nightly

### PR DESCRIPTION
**Pull request by vfreex**
4.11+ aarch64 nightlies have blocking tests like x86_64.

### CODE REVIEW

**Comment by vfreex** [comment]
Tested with https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/hack/job/yuxzhu/job/aos-cd-builds/job/build%252Fbuild-sync/3/

**Review by joepvd — APPROVED** [review]
/lgtm
/approve

**Comment by vfreex** [comment]
Fixed flake8. Merging

**Pull request merged**
