### PR TITLE
[ART-6052] migrate promote job steps to python

### PR DESCRIPTION
**Pull request by Ximinhan**
In this pr I did the following work:
- move mirror binary step into promote job
  - in this step I use openshift-client to invoke oc cli and get results, also use python lib to do the archive work and calc sha256sum
- move sign artifacts step into promote job
  - in this step I use jenkinsapi to invoke sign artifacts job
- move channel prs step into promote job
  - similar to previous step also implement with jenkinsapi, also update the build_microshift job invoke method
- move validate rhsa step into promote job
  - invoke elliott cli to do that in python
- add attach builds and check microshift bugs step in promote job
  - I update the build_microshift job it will store microshift nvrs in each build's description so nvrs can be easily get for attach and check step
  - and also update build_microshift, move the create pr step into promote job and in create pr function merge the pr after it created, so build_microshift job only do the build work 
  - invoke elliott cli to do that in python
- move send email step into promote job
  - use the send mail function in lib
- trigger microshift_sync job for EC after microshift job complete
- move sendCImessage to python
  - use stomp lib to send message

======
this pr replace the work of https://github.com/openshift/aos-cd-jobs/pull/3507 https://github.com/openshift-eng/aos-cd-jobs/pull/3553

### CODE REVIEW

**Comment by thegreyd** [comment]
This is too many set of changes for 1 PR to review and test - @Ximinhan I would like us to break it down to 
1) Convert groovy logic to python - this introduces no functional changes
    - This can also be 2 PRs, one which is porting trigger other jobs logic, and another which is doing groovy -> python logic. The reason being the first 1 can be reviewed/merged/tested trivially, while second one can take sometime.
2) Microshift changes

I'm curious if you've tested this?
```python
job = self.jenkins_client.get_job("signing-jobs/signing%2Fsign-artifacts")
build = job.invoke(build_params=params).block_until_building()
```

Since @locriandev finding in https://github.com/openshift-eng/aos-cd-jobs/pull/3418 was that multibranch pipeline can't recieve remote triggers..

**Comment by Ximinhan** [comment]
@thegreyd  for the jenkins lib I tested with build-sync job, I think jenkinsapi can handle jobs very well and it is more convenient than we use native post request now

**Comment by Ximinhan** [comment]
split the steps changes into https://github.com/openshift-eng/aos-cd-jobs/pull/3577

**Comment by ashwindasr** [comment]
If https://github.com/openshift-eng/aos-cd-jobs/pull/3925 is merged, please migrate this PR to art-tools, if not urgent.
If urgent, please create a duplicate PR to art-tools.

**Comment by Ximinhan** [comment]
this pr is outdated

**Pull request closed without merging**
