### PR TITLE
[ART-7730] Update scan-osh job to use new pyartcd command

### PR DESCRIPTION
**Pull request by ashwindasr**
Ready to be merged after https://github.com/openshift-eng/art-tools/pull/51. 

_Requesting lgtm and approve_

[Test](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/hack/job/ashwin-aos-cd-jobs/job/build%252Fscan-osh-new/42/) to make sure both NVRS and ALL_BUILDS params aren't enabled together.
[Test](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/hack/job/ashwin-aos-cd-jobs/job/build%252Fscan-osh-new/41/console) run with ALL_BUILDS and CHECK_TRIGGERED

### CODE REVIEW

**Comment by ashwindasr** [comment]
Once merged, locks in redis have to be deleted

**Comment by thegreyd** [comment]
I would say, when art-tools is merged also bump art-tools in this PR so changes can go in at the same time

**Pull request merged**
